[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
FermionicHilbertSpaces = "82e5dd95-83c3-46b2-a303-acc930c81756"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LowRankMatrices = "e65ccdef-c354-471a-8090-89bec1c20ec3"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
