[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FermionicHilbertSpaces = "82e5dd95-83c3-46b2-a303-acc930c81756"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
LowRankMatrices = "e65ccdef-c354-471a-8090-89bec1c20ec3"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
